### ISSUE TITLE
Feature request: a maxLength slider

### ISSUE THREAD

**Issue by dxinteractive** [bigdatr/semantic-fauna#7]
Many adjective-animal combos are quite long (such as `"black-and-white-irukandji-jellyfish"`, `"inconsequential-blue-tongued-lizard"` and `"well-documented-frilled-neck-lizard"`), might be nice to have a slider to force semantic fauna to be under a certain char limit.

Like `"wet-bat"` or `"big-bee"`

**Comment by dancoates** [comment]
This is added now
